- name: message from main
  debug:
    msg: "message from main"

- name: print variable - role default
  debug:
    msg: "from_roles_defaults - {{ from_roles_defaults }}"

- name: print variable - roles var
  debug:
    msg: "from_roles_vars - {{ from_roles_vars }}"

- name: demo import task
  ansible.builtin.import_tasks: import.yml

- name: demo include task
  ansible.builtin.include_tasks: import.yml

- name: Demo rol import
  ansible.builtin.import_role:
     name: Demo

- name: Demo role include
  ansible.builtin.include_role:
    name: Demo

- name: Demo role another include task
  ansible.builtin.include_role:
    name: Demo
    tasks_from: Another1.yml
