- name: message from main
  debug:
    msg: "message from main"

- name: print variable - role default
  debug:
    msg: "from_roles_defaults - {{ from_roles_defaults }}"

- name: print variable - roles var
  debug:
    msg: "from_roles_vars - {{ from_roles_vars }}"

- name: demo import task
  ansible.builtin.import_tasks: import.yml
