- name: variable demo from ini
  hosts: all
  tasks:
    - name: print Inventory variable host
      debug:
        msg: "from_ini_host - {{ from_ini_host }}"

    - name: print Inventory  group
      debug:
        msg: "from_ini_host - {{ from_ini_group }}"



    - name: print variable - play file
      debug:
        msg: "from_file - {{ from_file }}"

- name: variable demo from role
  hosts: all
  roles:
    - sample
    -
- name: variable demo from taks
  hosts: all
  tasks:
    - name: print variable - play level
      debug:
        msg: "from_task - {{ from_task }}"
      vars:
        from_task: 700

