- name: setup user
  hosts: all
  become: yes
  tasks:
    - name: Create appuser
      ansible.builtin.user:
        name: appuser
        system: yes
        shell: /bin/false
        create_home: no

    - name: remove /app
      ansible.builtin.file:
        path: /app
        state: absent

    - name: create /app folder
      ansible.builtin.file:
        path: /app
        state: directory

    - name: downloading nodejs
      ansible.builtin.shell: curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -

    - name: installing nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present


    - name: copy user service
      ansible.builtin.copy:
        src: user.service
        dest: /etc/systemd/system/user.service

    - name: unarchive cart content
      ansible.builtin.unarchive:
        src: https://raw.githubusercontent.com/raghudevopsb89/roboshop-microservices/main/artifacts/user.zip
        dest: /app
        remote_src: yes

    - name: Download App Dependencies
      ansible.builtin.shell: npm install --production
      args:
        chdir: /app

    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /app
        owner: appuser
        group: appuser
        recurse: yes
        mode: 'o-rwx'

    - name: user start
      ansible.builtin.systemd_service:
        name: user
        state: started
        enabled: yes
        daemon_reload: yes





#
#  curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -
#dnf install -y nodejs
#cp user.service /etc/systemd/system/user.service
#
#
#useradd -r -s /bin/false appuser
#rm -rf /app
#mkdir -p /app
#
#curl -L -o /tmp/user.zip https://raw.githubusercontent.com/raghudevopsb89/roboshop-microservices/main/artifacts/user.zip
#cd /app
#unzip /tmp/user.zip
#npm install --production
#chown -R appuser:appuser /app
#chmod o-rwx /app -R
#
#systemctl daemon-reload
#systemctl enable user
#systemctl restart user